app/routes.php
<?php

require "pattern.php";
require "modelBind.php";

Route::get('/', ['as' => 'home', 'after' => 'incview', 'uses' => 'HomeController@showWelcome']);

Route::group(['prefix' => 'slack', 'after' => 'incview'], function () {
	Route::get('', ['as' => 'slackinv.new', 'uses' => 'SlackController@create']);
	Route::get('create', ['as' => 'slackinv.new', 'uses' => 'SlackController@create']);
	Route::post('store', [ 'before' => 'crsf' , 'as' => 'slackinv.new', 'uses' => 'SlackController@store' ]);
	Route::get('thankyou', ['as' => 'slackinv.thankyou', 'uses' => 'SlackController@thankyou']);	
});

Route::group(['prefix' => 'auth'], function () {
	Route::get('login', ['as' => 'login', 'uses' => 'AuthController@getLogin' ]);
	Route::post('login', [ 'before' => 'crsf' , 'as' => 'login', 'uses' => 'AuthController@postLogin' ]);
	Route::get('logout', ['before' => 'auth' , 'as' => 'logout', 'uses' => 'AuthController@logout' ]);
	Route::get('forgotpass', ['as' => 'forgotpass', 'uses' => '@' ]);
	
});

Route::group(['prefix' => 'story', 'after' => 'incview'], function () {
	Route::get('{storyId}/show', ['as' => 'story.show', 'uses' => 'StoryController@show' ]);
	Route::post('{storyId}/comment/leave', [ 'before' => 'crsf' , 'as' => 'story.comment.leave', 'uses' => 'CommentController@store' ]);
});

Route::group(['prefix' => 'backend', 'before' => 'adminAccess'], function() {
	
	Route::get('home', ['as' => 'bhome', 'uses' => 'BackendController@index' ]);
	
	Route::get('stat', ['as' => 'backend.stat', 'uses' => 'BackendController@stat' ]);
	
	Route::group(['prefix' => 'category'], function() {
		Route::get('index', ['as' => 'category.index', 'uses' => 'CategoryController@index' ]);
		Route::get('new', ['as' => 'category.new', 'uses' => 'CategoryController@create' ]);
		Route::post('new', [ 'before' => 'crsf' , 'as' => 'category.new', 'uses' => 'CategoryController@store' ]);
		Route::get('{catId}/delete', ['as' => 'category.destroy', 'uses' => 'CategoryController@destroy' ]);

	});
	Route::group(['prefix' => 'story'], function() {
	
		Route::get('new', ['as' => 'story.new', 'uses' => 'StoryController@create' ]);
		Route::post('new', [ 'before' => 'crsf' , 'as' => 'story.new', 'uses' => 'StoryController@store' ]);
		Route::get('index', ['as' => 'story.index', 'uses' => 'StoryController@index' ]);
		Route::get('{storyId}/delete', ['as' => 'story.destroy', 'uses' => 'StoryController@destroy' ]);
		Route::get('{storyId}/comments', ['as' => 'story.comment.index', 'uses' => 'CommentController@story' ]);
	});

	Route::group(['prefix' => 'comment'], function () {

		Route::get('index', ['as' => 'comment.index', 'uses' => 'CommentController@index' ]);
		Route::get('notchecked', ['as' => 'comment.notchecked', 'uses' => 'CommentController@notchecked' ]);
		Route::get('{commentId}/show', ['as' => 'comment.show', 'uses' => 'CommentController@show' ]);
		Route::get('{commentId}/approve', ['as' => 'comment.approve', 'uses' => 'CommentController@approve' ]);
		Route::get('{commentId}/ignore', ['as' => 'comment.ignore', 'uses' => 'CommentController@ignore' ]);
		Route::get('{commentId}/delete', ['as' => 'comment.destroy', 'uses' => 'CommentController@destroy' ]);
		Route::get('{commentId}/reply', ['as' => 'comment.get.reply', 'uses' => 'CommentController@getReply' ]);
		Route::post('{commentId}/reply', [ 'before' => 'crsf', 'as' => 'comment.reply', 'uses' => 'CommentController@reply' ]);
	});

	Route::group(['prefix' => 'slack'], function () {

		Route::get('index', ['as' => 'slack.index', 'uses' => 'SlackController@index' ]);
	});
	Route::group(['prefix' => 'config'], function () {

		Route::get('index', ['as' => 'config.index', 'uses' => 'BackendController@config' ]);
	});

	Route::get('mig', ['as' => 'mig', 'uses' => 'BackendController@migrate' ]);
	
});

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;

class User extends Eloquent implements UserInterface {

	use UserTrait;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password');

	public function getName() {
		return $this->firstname . ' ' . $this->lastname;
	}
	public function setPasswordAttribute($value) {
		$this->attributes['password'] = Hash::make($value);
	}

	public function story() {
		return $this->hasMany('Story', 'author');
	}
}

app/views/layouts/private/ajaxModal.blade.php
@yield('style')
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<div class="inTitle"><h4 class="modal-title">@yield('title')@yield('inTitle')</h4></div>
		</div>
		@yield('formopen')
			<div class="modal-body">
				@yield('content')
			</div>
			<div class="modal-footer">
				@yield('footer')
				&nbsp; یا <a href="#" class="btn" data-dismiss="modal">بستن</a>
			</div>
		</form>
	</div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
@yield('script')

app/views/layouts/private/master.blade.php
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>@yield('title') - {{ SConfig::get('system.name') }}</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<!-- Loading Bootstrap -->    
		{{ HTML::style("bootstrap/css/bootstrap.min.css") }}
		{{ HTML::style('css/dashboard.css') }}	
		<!-- fontawesome styles  -->
		{{ HTML::style("font-awesome/css/font-awesome.min.css") }}
		{{ HTML::style("css/style.css") }}

		<link rel="shortcut icon" href="images/favicon.ico">

		<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
		<!--[if lt IE 9]>
			{{ HTML::script("js/html5shiv.js") }}
			{{ HTML::script("js/respond.min.js") }}
		<![endif]-->
		@yield('style')
	</head>
	<body>		
		<!-- include('layouts.public.partial.menu2') -->

		<div class="container">
	      	<div class="row">
				@include('layouts.private.menu')
				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					<div class="inTitle"><h1 class="sub-header">@yield('title')@yield('inTitle')</h1></div>
					@yield('breadcrumbs')
					@yield('content')
				</div>
				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					@include('layouts.partial.footer')
				</div>
			</div>
		</div>
		<div class="modal-dialog" id="ajaxLoading" style="display:none">
			<div class="modal-content">
				<p>
					<div><i class="fa fa-3x fa-spinner"></i></div>
					<h4>لطفاً کمی تأمل فرمائید.</h4>
				</p>
			</div>
		</div>

		<!-- Load JS here for greater good =============================-->
		{{ HTML::script("js/jquery-2.0.3.min.js") }}
		{{ HTML::script("bootstrap/js/bootstrap.min.js") }}
		{{ HTML::script("js/bootbox.min.js") }}
		{{ HTML::script('js/modalcreator.js') }}
		{{ HTML::script('js/jquery.centerize.js') }}
		<script type="text/javascript">
			$( document ).ajaxStart(function() {
				$("#ajaxLoading").show().center();
			});
			$( document ).ajaxStop(function(){
				$("#ajaxLoading").hide();
			});
		</script>
		@yield('script')
	</body>
</html>

app/views/layouts/private/menu.blade.php
<div class="col-sm-3 col-md-2 sidebar">
	<ul class="nav nav-sidebar">
		<li class="nav-header">منو اصلی</li>
		<li><a href="{{ URL::route('home') }}" target="_blank"><i class="fa fa-home"></i> صفحه اصلی</a></li>
		<li><a href="{{ URL::route('config.index') }}"><i class="fa fa-gear"></i> تنظیمات سایت</a></li>
		<li><a href="{{ URL::route('logout') }}"><i class="fa fa-power-off"></i> خروج</a></li>
	</ul>
	<ul class="nav nav-sidebar">
		<li class="nav-header">یادداشت</li>
		<li><a href="{{ URL::route('story.new') }}"><i class="fa fa-pencil"></i> درج یادداشت جدید</a></li>
		<li><a href="{{ URL::route('story.index') }}"><i class="fa fa-newspaper-o"></i> مدیریت یادداشت ها</a></li>
	</ul>
	<ul class="nav nav-sidebar">
		<li class="nav-header">دسته بندی</li>
		<li><a data-toggle="ajaxModal" href="{{ URL::route('category.new') }}"><i class="fa fa-plus-square"></i> دسته بندی جدید</a></li>
		<li><a href="{{ URL::route('category.index') }}"><i class="fa fa-bars"></i> مدیریت دسته بندی ها</a></li>
	</ul>
	<ul class="nav nav-sidebar">
		<li class="nav-header">دیدگاه ها</li>
		<li><a href="{{ URL::route('comment.notchecked') }}"><i class="fa fa-plus-square"></i> دیدگاه های چک نشده</a></li>
		<li><a href="{{ URL::route('comment.index') }}"><i class="fa fa-bars"></i> مدیریت دیدگاه ها</a></li>
	</ul>
	<ul class="nav nav-sidebar">
		<li class="nav-header">اسلک</li>
		<li><a href="{{ URL::route('slack.index') }}"><i class="fa fa-plus-square"></i> دعوتنامه اسلک</a></li>
	</ul>
</div>